#!/usr/bin/env bash
# Hyprland config, applied with the include model:
#
#   config/hypr/<name>.lua          shared by every machine
#   hosts/<host>/hypr/<name>.lua    appended for this machine only
#         |
#         v   generated, owned outright, overwritten on every run
#   ~/.config/hypr/omarchy-setup/<name>.lua
#         ^
#         |   one constant require line inside a fenced block
#   ~/.config/hypr/<name>.lua       Omarchy's file, touched once
#
# The block written into Omarchy's file never changes, whatever the content
# does, so a re-run or a config edit never touches the system file again, and
# `omarchy update` migrations keep patching everything outside the fence.
source "${OMARCHY_SETUP_LIB:?}/common.sh"

HYPR="$HOME/.config/hypr"
OWNED="$HYPR/omarchy-setup"
BASE_DIR="$OMARCHY_SETUP_ROOT/config/hypr"
HOST_DIR="$OMARCHY_SETUP_ROOT/hosts/$SETUP_HOST/hypr"

# The require goes through Omarchy's require_optional, so a missing owned file
# (someone deleted the directory by hand) is skipped instead of breaking the
# whole Hyprland config. Errors inside the file still surface normally.
#
# The "hypr." prefix is load-bearing: Omarchy's bootstrap.lua evicts only the
# "default.hypr", "hypr" and "omarchy.current.theme" prefixes from
# package.loaded on reload. A module under any other name would be cached, and
# `hyprctl reload` would keep the old content until the next login.
require_line() {
  printf 'require("default.hypr.require_optional").module("hypr.omarchy-setup.%s")\n' "$1"
}

# Union of config names from the shared dir and this host's dir.
declare -A names=()
for d in "$BASE_DIR" "$HOST_DIR"; do
  [[ -d $d ]] || continue
  for f in "$d"/*.lua; do
    [[ -f $f ]] && names["$(basename "$f" .lua)"]=1
  done
done

render() {
  local name=$1 base="$BASE_DIR/$1.lua" host="$HOST_DIR/$1.lua"
  printf -- '-- Generated by omarchy-setup. Do not edit: every run overwrites it.\n'
  printf -- '-- Source: config/hypr/%s.lua' "$name"
  [[ -f $host ]] && printf ' + hosts/%s/hypr/%s.lua' "$SETUP_HOST" "$name"
  printf '\n-- Loaded from ~/.config/hypr/%s.lua through its fenced require line.\n\n' "$name"
  [[ -f $base ]] && cat "$base"
  if [[ -f $host ]]; then
    [[ -f $base ]] && printf '\n'
    printf -- '-- host: %s\n' "$SETUP_HOST"
    cat "$host"
  fi
}

# Catch a typo before Hyprland does: a broken owned file surfaces only as a
# `hyprctl configerrors` line after reload, and not at all over ssh.
check_lua() {
  command -v luac >/dev/null 2>&1 || return 0
  luac -p - 2>&1 | sed 's/^luac: stdin:/  line /' >&2
  return "${PIPESTATUS[0]}"
}

for name in $(printf '%s\n' "${!names[@]}" | sort); do
  target="$HYPR/$name.lua"
  if [[ ! -f $target ]]; then
    warn "no such Omarchy config: $target (skipping '$name')"
    continue
  fi
  render "$name" | check_lua || die "syntax error in hypr config '$name'"
  render "$name" | write_owned_file "$OWNED/$name.lua"
  require_line "$name" | write_managed_block "$target" "$name" '--'
done

# A name dropped from the repo takes its owned file and its require line with
# it, so the machine does not keep applying config that no longer exists here.
for f in "$OWNED"/*.lua; do
  [[ -f $f ]] || continue
  name=$(basename "$f" .lua)
  [[ -n ${names[$name]:-} ]] && continue
  info "removing stale hypr config: $name"
  run rm -f -- "$f"
  remove_managed_block "$HYPR/$name.lua" "$name" '--'
done

hypr_reload
